"""Draw every figure and write the JNU results table."""
import json, os
import numpy as np
import figures, paths

RES, FIGS = paths.RESULTS, paths.FIGS


def main():
    figures.use_style()
    os.makedirs(FIGS, exist_ok=True)
    S = json.load(open(os.path.join(RES, "summary.json")))
    C = json.load(open(os.path.join(RES, "controls.json")))
    A = json.load(open(os.path.join(RES, "arch3.json")))
    grid = json.load(open(os.path.join(RES, "jnu_grid.json")))

    ex = C["example_pair"]
    per_bin = C["axis"]["per_bin_log"]
    figures.fig_identity(os.path.join(FIGS, "fig1_identity.pdf"),
                         np.array(ex["a"]), np.array(ex["b"]),
                         np.array(ex["centres"]), C["shift_identity"], per_bin)
    print("fig 1")

    # architecture control: medians over seeds, both datasets
    rows = []
    for ds in ("jnu", "cwru"):
        for fe in ("lfes", "ses", "order"):
            r = dict(dataset=ds, front_end=fe)
            for k in ("rf_out", "lr_out", "rf_in", "lr_in"):
                r[k] = float(np.mean([x[k] for x in A["shallow"]
                                      if x["dataset"] == ds and x["front_end"] == fe]))
            for k in ("cnn_out", "cnn_in"):
                r[k] = float(np.median([x[k] for x in A["cnn"]
                                        if x["dataset"] == ds and x["front_end"] == fe]))
            rows.append(r)
    figures.fig_architecture(os.path.join(FIGS, "fig2_architecture.pdf"), rows)
    print("fig 2")

    figures.fig_jnu(os.path.join(FIGS, "fig3_jnu.pdf"), S)
    figures.fig_margin(os.path.join(FIGS, "fig4_margin.pdf"), grid, S)
    figures.fig_sim(os.path.join(FIGS, "fig5_sim.pdf"), S)
    print("figs 3 to 5")

    # the JNU table, generated rather than typed
    tab = [r"\begin{tabular}{@{}llrrr@{}}", r"\toprule",
           r"Axis & Method & in-speed & unseen speed & $M$ \\", r"\midrule"]
    t = S["jnu_by_front_method"]
    for fe, lab in (("ses", "linear"), ("lfes", "log")):
        for me, mlab in (("fedavg", "FedAvg"), ("prox", "FedProx"),
                         ("proto", "prototype alignment")):
            k = f"{fe}|{me}"
            fi = "acc_in_proto" if me == "proto" else "acc_in_linear"
            fo = "acc_out_proto" if me == "proto" else "acc_out_linear"
            tab.append(f"{lab} & {mlab} & {100*t[k][fi][0]:.1f} & "
                       f"{100*t[k][fo][0]:.1f} $\\pm$ {100*t[k][fo][1]:.1f} & "
                       f"{t[k]['M'][0]:.2f} \\\\")
        if fe == "ses":
            tab.append(r"\addlinespace")
    tab += [r"\bottomrule", r"\end{tabular}"]
    with open(os.path.join(paths.PUBLISH, "jnu_table.tex"), "w") as fh:
        fh.write("% generated by make_figs.py -- do not edit\n" + "\n".join(tab) + "\n")
    print("wrote jnu_table.tex")

    # the simulated sweep against the ball defect order, when it has been run
    B = S.get("sim_ball_order")
    if B:
        tab = [r"\begin{tabular}{@{}lccccc@{}}", r"\toprule",
               r"Ball order & \multicolumn{2}{c}{Spearman, log axis} & "
               r"Spearman, linear & Log accuracy, \% & Paired / class-mean \\",
               r"\cmidrule(lr){2-3}",
               r" & mean curve & per seed & mean curve & $1 < \rho \le 2$ & displacement \\",
               r"\midrule"]
        for bo in sorted({float(k.split("|")[0]) for k in B}):
            g, l = B[f"{bo:.2f}|lfes"], B[f"{bo:.2f}|ses"]
            tab.append(f"{bo:.2f} & {g['spearman_M_acc']:.2f} & "
                       f"{g['spearman_seed_mean']:.2f} $\\pm$ {g['spearman_seed_sd']:.2f} & "
                       f"{l['spearman_M_acc']:.2f} & "
                       f"{100*g['acc_mid_lo']:.1f} to {100*g['acc_mid_hi']:.1f} & "
                       f"{g['underest_lo']:.2f} to {g['underest_hi']:.2f} \\\\")
        tab += [r"\bottomrule", r"\end{tabular}"]
        with open(os.path.join(paths.PUBLISH, "ball_order_table.tex"), "w") as fh:
            fh.write("% generated by make_figs.py -- do not edit\n" + "\n".join(tab) + "\n")
        print("wrote ball_order_table.tex")


if __name__ == "__main__":
    main()
